version: '3.9'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    environment:
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - N8N_HOST=127.0.0.1
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - WEBHOOK_URL=127.0.0.1:5678
      - N8N_DEFAULT_CORS=*
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  n8n_data: